### ISSUE TITLE
Found an issue on parsing the Messages

### ISSUE THREAD

**Issue by negue** [dnaka91/go-vmcparser#1]
Using the Live-Data it couldn't parse a Message when it had more than 28 Buffer Length

I had to use this instead, maybe there is a better to do this

```go
// in the parseBoneTransform Function
	if len(data) <= 28 {
		return nil, InvalidBufferLengthError{Length: len(data), Expected: []int{28}}
	}
```

**Comment by dnaka91** [comment]
Oh that is interesting. According to spec, it should be exactly 28 bytes long, 7 floats, each 4 bytes long. 

And further, for UDP messages, it's said they should be self-contained, meaning one UDP packet should contain a single OSC message with the proper size.

So the sending app might not follow the spec here, maybe 🤔.

Could you tell me the length of the actual data (should be in the error message)? I'm curious how long it is, and what might be the additional data. Also, if you don't mind, could you pass the raw data on that it is failing? Perhaps in hex or as a file.

If it is a rather fixed length, like always 4, 8 or 12 extra bytes, then it might be some extra argument. If it always changes, the app possibly sends 2 messages in a single payload.

**Comment by dnaka91** [comment]
Had a look at the official VMC for Unity repo, and they expect exactly 8 values as well, first 1 string, then 7 floats: [link](https://github.com/gpsnmeajp/EasyVirtualMotionCaptureForUnity/blob/a79a8b0f48c25632e3b208541a96507672db424e/EVMC4U/ExternalReceiver.cs#L529-L573). Didn't look at how they parse the OSC message, so they might just drop any trailing data when parsing.

But, after we find out what the data is, I can of course change all the length checks to be more permissive. Not requiring an exact length, but instead only check that it's at least long enough to contain the expected data. That way, it will not care about any trailing data anymore.

**Comment by dnaka91** [comment]
I just went ahead and changed the parsing, so it'll accept (or rather ignore) any trailing data, and just ensures that there is at least enough data to read parse the expected fields.

Still, would be great to figure out what the trailing data is.

**Comment by negue** [comment]
> Could you tell me the length of the actual data (should be in the error message)?

2022-07-03T14:52:31+02:00 | FATAL | failed to parse VMC message: got 1496 bytes of data, expected exactly 28

there were bytes from Position 0 to 27 but after that everything is just 0 

after checking my code - it seems that I didn't used the already sliced Array of `filledBuffer := buf[:n]` but instead used `buf` as argument to vmc.ParseMessage ... yep that explains it :D  - sorry for wasting your time
